version: '3.7'

services:
  #Backend api
  crypto-api:
    build: ./
    ports:
      - 3000:3000
    environment:
      - PG_HOST=db
      - PG_DB_NAME=crypto
      - PG_PASSWORD=postgres
      - PG_USER=postgres
      - PG_POST=5432
    depends_on:
      - db  

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres    
