version: '3.7'

services:
  #Backend api
  crypto-api:
    build: ./
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db  

    db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres    
